### PR TITLE
[SDK-4362] Rewrite QS to use Django 4.2 (LTS) from 2.2 (EOL'd), and PyJWT 2.7 from 1.7 (EOL'd)

### PR DESCRIPTION
**Pull request by evansims**
This PR:

- Rewrites the quickstart to use Django 4.2 (LTS), the current recommended release. The previous example used Django 2.2, which is no longer supported. The sister quickstart to this, [auth0-django-web-app](https://github.com/auth0-samples/auth0-django-web-app), has already been updated to use 4.2.
- Upgrades PyJWT to 2.7 (up from 1.7, which is no longer supported.)
- 🔒 Resolves 15 Snyk warnings from vulnerabilities in unsupported dependencies.

@adamjmcgrath I'd appreciate your input on these changes. Once I get your 👍 on the changes, I'll update the test suite to pass and use GitHub Actions, and update the written QS guide to match these changes.

(This is being tracked internally as SDK-4362.)

### CODE REVIEW

**Comment by romanv-jazwares** [comment]
Just a question on this Pull Request, coming from someone who is looking to integrate Auth0 into an existing DRF application. This seems to drop the Django Rest Framework implementation. Are there plans to also provide an example with DRF?

**Comment by evansims** [comment]
Hi @romanv-jazwares, thanks for taking a look!

While the current version of this QuickStart includes DRF as a dependency, as I was updating this code, I didn’t identify anything that was particularly specific (in terms of
how we’re demonstrating authorization) to DRF that justified including the dependency.

I think perhaps introducing a separate example folder specifically for DRF integration would make sense, as bandwidth allows. Given that there are just so many REST frameworks out there for Django, I think it’s good to have a minimal starter integration example that doesn’t rely on anything extra, dependency speaking.

I agree though, a separate DRF integration example would be good to offer.

**Comment by romanv-jazwares** [comment]
Thanks for the quick reply @evansims! Understood, I'll work through implementing this for our particular DRF setup. Either way, I appreciate all the work you and the rest of the team put into these!

**Review by adamjmcgrath — COMMENTED** [review]
lgtm 👍

**Pull request merged**
